#!/bin/sh
set -e  # Exit immediately if any command fails

cd desktop_app

# Run lint-staged
pnpm lint-staged

# Run tests
echo "Running tests..."
pnpm test

# Run codegen
echo "Running codegen..."
pnpm codegen:all
